-- 创建商品分类表
CREATE TABLE IF NOT EXISTS product_category (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  icon VARCHAR(500),
  sort INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 创建商品表
CREATE TABLE IF NOT EXISTS product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  merchantId INT NOT NULL,
  categoryId INT,
  name VARCHAR(100) NOT NULL,
  coverImage VARCHAR(500),
  price DECIMAL(10,2) NOT NULL,
  stock INT DEFAULT 0,
  sales INT DEFAULT 0,
  description TEXT,
  status TINYINT DEFAULT 0,
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 创建餐厅表
CREATE TABLE IF NOT EXISTS restaurant (
  id INT AUTO_INCREMENT PRIMARY KEY,
  merchantId INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  coverImage VARCHAR(500),
  address VARCHAR(200),
  phone VARCHAR(20),
  businessHours VARCHAR(50),
  avgPrice DECIMAL(10,2),
  specialty VARCHAR(200),
  description TEXT,
  status TINYINT DEFAULT 1,
  longitude DECIMAL(10,6),
  latitude DECIMAL(10,6),
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 创建菜品表
CREATE TABLE IF NOT EXISTS dish (
  id INT AUTO_INCREMENT PRIMARY KEY,
  restaurantId INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  image VARCHAR(500),
  price DECIMAL(10,2) NOT NULL,
  category VARCHAR(50),
  description VARCHAR(500),
  isRecommended TINYINT DEFAULT 0,
  status TINYINT DEFAULT 1,
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 创建农产品分类表
CREATE TABLE IF NOT EXISTS farm_product_category (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  icon VARCHAR(500),
  sort INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 创建农产品表
CREATE TABLE IF NOT EXISTS farm_product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  merchantId INT NOT NULL,
  categoryId INT,
  name VARCHAR(100) NOT NULL,
  coverImage VARCHAR(500),
  price DECIMAL(10,2) NOT NULL,
  unit VARCHAR(20),
  origin VARCHAR(100),
  stock INT DEFAULT 0,
  description TEXT,
  status TINYINT DEFAULT 1,
  createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
  updateTime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
